server:
  port: "8080"
  host: "localhost"

redis:
  address: "localhost:6379"
  password: ""
  db: 0

firestore:
  project_id: "your-gcp-project-id"
  credentials_file: "path/to/your/credentials.json" # e.g., ./configs/gcp-credentials.json

rabbitmq:
  url: "amqp://guest:guest@localhost:5672/"
  queue_name: "my_queue"
